### ISSUE TITLE
Server Update Todo

### ISSUE THREAD

**Issue by krissykrissy** [bwhsleepamu/access#1]
- [ ] Map all network drives on the server
- [ ] Troubleshoot LDAP Authentication
- [ ] Troubleshoot SSL Setup
- [ ]
